### ISSUE TITLE
Bug error on clicking checkbox email field

### ISSUE THREAD

**Issue by stefanpkc** [Bixie/pagekit-formmaker#6] opened 2015-11-19 03:52 UTC
This happens when you select ```Send submission confirmation to this address``` at ```/admin/formmaker/form/edit?id=1```

```
Uncaught TypeError: Cannot read property 'data' of
undefinedmodule.exports.watch.field.data.user_email
@ formmaker-email.js:116i.run
@ vue.min.js:6s
@ vue.min.js:6r
@ vue.min.js:6t
@ vue.min.js:6
```

**Comment by stefanpkc** [comment] 2015-11-20 15:25
This is the line: https://github.com/Bixie/pagekit-formmaker/blob/master/app/fields/email.vue#L58

**Comment by malles** [comment] 2015-11-23 18:56
related to #4, or probably the cause. I'll look into that. Thanks for reporting

**Comment by malles** [comment] 2015-12-12 16:26
Fixed with https://github.com/Bixie/pagekit-formmaker/commit/ac81ff6755822957d14eb1da8a0b84730a8b106f

**Closed by malles** 2015-12-12 16:26 UTC
