### ISSUE TITLE
Send confirm submission only to copy email

### ISSUE THREAD

**Issue by KevinSupertramp** [Bixie/pagekit-formmaker#7] opened 2015-12-23 12:26 UTC
Hello there,

First I want to thank you for this extension, it's really usefull ! Second I would like to know if it's possible to send the confirm submission only to my contact email, not the visitor one ? (Using the "Email copy of submission to" field).

What I would like to do is to receive an email to my contact mail when a new submission is sent without the visitor getting a confirmation mail.

Is it possible ?

Thank you!

**Comment by malles** [comment] 2015-12-23 13:15
That can be done by leaving the selected field for user-email blank. Mail will only be sent to the mailaddress in the input below it.
![image](https://cloud.githubusercontent.com/assets/5442402/11977086/8cf6d816-a97f-11e5-8c7c-9f49f015e614.png)
There could be a form that has no email field, that will still be sent to the admin address.

**Comment by KevinSupertramp** [comment] 2015-12-23 17:01
Hello,

Thank you, I thought about that and tried it before but it doesn't work for me.
Is it working for you ?

Best

**Comment by malles** [comment] 2015-12-25 15:31
It is not, I'm afraid. It was intended, but I see the code says different 😀
It will be fixed in future versions.

**Comment by KevinSupertramp** [comment] 2015-12-26 07:42
Okay thank you very much!

**Comment by amaierm** [comment] 2015-12-30 21:56
Same Problem here... 

But. Thanks for this extension!

**Comment by stefanpkc** [comment] 2016-01-05 07:30
https://github.com/Bixie/pagekit-formmaker/blob/master/src/Submission/MailHelper.php#L28
This line of code is responsible. If no email is set, it will return.
So perhaps fill in a backup@mydomain.com email or change the code.

**Closed** 2016-01-05 15:37 UTC

**Comment by malles** [comment] 2016-01-05 15:55
@stefanpkc That checks the adminmail, not the user mail. Admin mail must be present for mail function to work, I think that is reasonable.
I did add a warning and validation for it to make it more clear.
https://github.com/Bixie/pagekit-formmaker/commit/ee04fff664d56a5daf42dda0197c201600694fe1

**Comment by KevinSupertramp** [comment] 2016-01-05 20:25
Thanks a lot @malles !

**Comment by stefanpkc** [comment] 2016-01-06 00:18
@malles, I understand. But what if you don't want to send the mail to admin? Only to user mail? ;-)

**Comment by malles** [comment] 2016-01-06 12:02
That's not possible. If you spam the user, you deserve a copy.
